spring:
  application:
    name: crud-spring

  profiles:
    active: prod

  data:
    web:
      pageable:
        default-page-size: 10

  sql:
    init:
      mode: always

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method